name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
version: VERSION
core: 8.x
configure: config.sync

# Information added by drush on 2018-12-05
version: '8.6.4'
project: 'drupal'
datestamp: 1544011082